### ISSUE TITLE
Account Registration

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/plantlife#11]
EPIC: Authentication

As a **user** I want to **have my own account** so that **I can write my own posts as well as like and comment on other people's posts**

**Acceptance Criteria**
- [ ] User has to give the username
- [ ] User has can give the email address
- [ ] User has to set a password
- [ ] User needs to confirm password
- [ ] All input fields but email are required
- [ ] After successful registration user gets redirected to the homepage

**Tasks**

- [ ] Task 1: Implement registration form
- [ ] Task 2: Test functionality
