### ISSUE TITLE
View Settings

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/plantlife#12]
EPIC: Settings

As a user I want to **view the settings page** so that **I can see what my current settings are**

**Acceptance Criteria**
- [ ] User clicks on settings in the header instead of the sign in / sign up functionalities
- [ ] By clicking the link, user lands on the settings page

**Tasks**
- [ ] Task 1: Create new settings page
- [ ] Task 2: Link user avatar to the settings page
- [ ] Task 3: Settings page contains email, username, password, log out link
- [ ] Task 4: Test functionality
