### ISSUE TITLE
Change Settings

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/plantlife#13]
EPIC: Settings

As a **user** I want to **change my email address, username and/or password** so that **I can increase the security of my account**

**Acceptance Criteria**
- [ ] User can change email address by clicking on edit icon
- [ ] User can change password by typing the current and new password
- [ ] Changes re saved by clicking on "Update Settings" button

**Tasks**
- [ ] Task 1: Add edit icon to email address
- [ ] Task 2: Clicking on edit icon shows input fields
- [ ] Task 3: Clicking "Update Settings" button saves the changes
- [ ] Task 5: Test functionality
