### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/plantlife#14]
EPIC: Alerts

As a **user** I want to **see alerts such as a success or error message** so that I **know if an action was a success or if it failed**

**Acceptance Criteria**
Show success or error alerts after:
- [ ] Register
- [ ] Log In
- [ ] Log Out
- [ ] Write a post
- [ ] Edit a post
- [ ] Comment on a post
- [ ] Delete a post
- [ ] Edit email address
- [ ] Change password

**Tasks**
- [ ] Task 1: Implement alerts
- [ ] Task 2: Test alerts
