### ISSUE TITLE
View Profile

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/plantlife#15]
EPIC: Profile

As a **user** I want to **have the option to view a user profile page** so that **I can have insights in statistics and other data.**

**Acceptance Criteria**
- [ ] User can view a profile page
- [ ] Profile page consists of profile image, bio and location
- [ ] Users can see a profile page by clicking on the username

**Tasks**
- [ ] Task 1: Add profile page
- [ ] Task 2: Access page by clicking on username
- [ ] Task 3: Display profile picture, bio and location
