### ISSUE TITLE
Edit Comment

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/plantlife#18]
EPIC: Posts

As a **comment owner** I want to **edit my own comment** so that **I can update it at any time**

**Acceptance Criteria**
- [ ] User can edit comment after clicking edit icon
- [ ] Adding changes and clicking the update button will apply changes

**Tasks**
- [ ] Task 1: Add edit link next to comment
- [ ] Task 2: Test functionality
