### ISSUE TITLE
Delete Comment

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/plantlife#19]
EPIC: Posts

As a **post owner** I want to **have the option to delete my own comment** so that **it is not visible to other users without me wanting it.**

**Acceptance Criteria**
- [ ] User clicks on delete icon to delete comment
- [ ] User sees warning page before deleting the comment

**Tasks**
- [ ] Task 1: Add delete icon next to the comment
- [ ] Task 2: Show warning page when user wants to delete an article
- [ ] Task 3: Test functionality
