### ISSUE TITLE
Create Post

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/plantlife#2]
EPIC: Posts

As a **user** I want to **write a post** so that **I can share my knowledge and tips about plants**

**Acceptance Criteria**
- [ ] User clicks on the button "Plant Post in header which opens the editor
- [ ] User can add title, image and content of the post and then publish it by clicking "Submit Post"

**Tasks**
- [ ] Task 1: Create new page for writing a post
- [ ] Task 2: Add button to header and link to new post page
- [ ] Task 3: Add form that consists of a headline, image, content and a submit button
- [ ] Task 4: Publish article by clicking submit button
- [ ] Task 6: Test functionality
