### ISSUE TITLE
View Comments

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/plantlife#20]
EPIC: Profile

As a **logged in user** I want to **have the option to view the comments of a post** so that **I can can read what other users think about the post*

**Acceptance Criteria**
- [ ] Users click on the comment icon and a modal opens with all comments

**Tasks**
- [ ] Task 1: Add comment icon on post
- [ ] Task 2: Access comments by clicking on the comment icon
