### ISSUE TITLE
Search For Posts and Users

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/plantlife#23]
EPIC: Post List

As a **logged in user** I want to **have the ability to search for specific posts and users** so that **I can find the information that interests me quicker**

**Acceptance Criteria**
- [ ] Users sees search bar on top of post list
- [ ] Typing a post name or username will filter the postfeed

**Tasks**
- [ ] add search bar on post list page
- [ ] filter page depending on search input
