### ISSUE TITLE
Save A Post

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/plantlife#26]
EPIC: Posts

As a **logged in user** I want to **save a post** so that **I can view the post at a later time*

**Acceptance Criteria**
- [ ] At the bottom of each post is a save icon 
- [ ] Clicking on save icon will save the post and turn it green
- [ ] Clicking again will remove the posts from the saved status

**Tasks**
- [ ] Task 1: Add save icon
- [ ] Task 2: Change icon color when clicked
