### ISSUE TITLE
Edit Password

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/plantlife#32]
EPIC: Profile

As a **profile owner** I want to change my password so that **I can increase the security of my account**

**Acceptance Criteria**
- [x]  User can edit their password

**Tasks**
- [x]  Task 1: Add edit password page
- [x]  Task 2: Access page by clicking on edit icon on profile page
