### ISSUE TITLE
Edit Username

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/plantlife#33]
EPIC: Profile

As a **logged in user** I want to **change my username** so that **I can control what is shown to other users**

**Acceptance Criteria**
- [ ]  User can edit their username

**Tasks**
- [ ]  Task 1: Add edit username page
- [ ]  Task 2: Access page by clicking on edit icon on profile page
