### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/plantlife#38]
EPIC: Notification

As a **logged in user** I want to **get notified about events** so that **I don't miss anything important or interesting**

**Acceptance Criteria**
- [ ] User can click on notification icon in NavBar to see notifications
- [ ] Notifications can be marked as read

**Tasks**
- [ ] Add notification icon to NavBar
- [ ] Add functionality to mark notifications as read
