### ISSUE TITLE
Delete Post

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/plantlife#4]
EPIC: Posts

As a **user** I want to **have the option to delete my own post** so that **it is not visible to other users without me wanting it.**

**Acceptance Criteria**
- [ ] User clicks on delete icon to delete post
- [ ] User sees warning page before deleting the post

**Tasks**
- [ ] Task 1: Add delete icon next to the posts' headlines
- [ ] Task 2: Show warning page when user wants to delete an article
- [ ] Task 3: Test functionality
