### ISSUE TITLE
View Post Feed

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/plantlife#41]
EPIC: Post List

As a **logged in user** I want to **see a list of all posts from people I follow** so that **I can I can read more posts of people I find interesting**

**Acceptance Criteria**
- [ ]  User click on "Post Feed" in header
- [ ]  User sees all posts from people they follow

**Tasks**

- [ ] Add Post feed page
