### ISSUE TITLE
Create Ads

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/plantlife#43]
EPIC: Marketplace

As a **logged in user** I want to **write an add** so that **I can sell or give away my plant(s)**

**Acceptance Criteria**
- [ ] User clicks on the button to create ad in header which opens the editor
- [ ] User can add title, plant type, availability, price, image, content and contact and then publish it by clicking "Create Advertisement"

**Tasks**
- [ ] Task 1: Create new page for writing an ad
- [ ] Task 2: Add button to header
- [ ] Task 3: Add form 
- [ ] Task 4: Publish ad by clicking submit button
- [ ] Task 6: Test functionality
