### ISSUE TITLE
Delete Ads

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/plantlife#45]
EPIC: Marketplace

As a **ad owner** I want to **have the option to delete my own ad** so that **it is not visible to other users without me wanting it.**

**Acceptance Criteria**
- [x] User clicks on delete icon to delete ad

**Tasks**
- [x] Task 1: Add delete icon next to the ads' headlines
- [x] Task 3: Test functionality
