### ISSUE TITLE
View List of Ads

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/plantlife#46]
EPIC: Marketplace

As a **user** I want to **see a list of all ads** so that **I can choose which one I want to read**

**Acceptance Criteria**
- [ ] User sees a list of all ads
- [ ] list is ordered by most recently added

**Tasks**
- [ ] Task 1: Show all ads on one page
- [ ] Task 2: List is ordered by most recently added
