### ISSUE TITLE
Comment on Post

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/plantlife#5]
EPIC: Posts

As a **user** I want to **comment on posts** so that **I can share my opinion and/or ask questions**

**Acceptance Criteria**
- [ ] On the bottom of each post is a message icon with the total number of comments
- [ ] Clicking on message icon will open the comments area
- [ ] Typing the comment and clicking the submit button will post the comment
- [ ] Above the input field is a list of all comments

**Tasks**
- [ ] Task 1: Add comment section at the bottom
- [ ] Task 2: Add comment icon that opens the comment section
- [ ] Task 3: Display comments
- [ ] Task 4: Test functionality
