### ISSUE TITLE
Post Feed

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/plantlife#6]
EPIC: Posts

As a **user** I want to **see a list of all posts** so that **I can choose which one I want to read**

**Acceptance Criteria**
- [ ] User sees a list of all posts
- [ ] list is ordered by most recently added

**Tasks**
- [ ] Task 1: Show all posts on one page
- [ ] Task 2: List is ordered by most recently added
