### ISSUE TITLE
Like a Post

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/plantlife#7]
EPIC: Posts

As a **user** I want to **like a post** so that **I can show my appreciation to other users**

**Acceptance Criteria**
- [ ] At the bottom of each post is a heart icon with the total number of likes
- [ ] Clicking on heart icon will turn it red and increase the amount of likes by one
- [ ] Clicking again will remove the like and turn it back to grey

**Tasks**
- [ ] Task 1: Add like icon and total amount of likes
- [ ] Task 2: Change icon color when clicked
- [ ] Task 3: Increase/decrease counter by 1 when clicked
- [ ] Task 4: Test functionality
