### ISSUE TITLE
Display Header

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/plantlife#8]
EPIC: Header

As a **user** I want to **see a header on top of the page** so that **I have a way to register, login and navigate through the website**

**Acceptance Criteria**
- [ ] Contains logo that will lead to homepage
- [ ] Displays log in link and sign up button
- [ ] Also add items: "Home", "Saved Posts", "Plant Lovers"

**Tasks**
