### ISSUE TITLE
Log In

### ISSUE THREAD

**Issue by dev-timm** [dev-timm/plantlife#9]
EPIC: Authentication

As a **user** I want to **log in** so that **I can like, comment and write posts**

**Acceptance Criteria**
- [ ] User has to type correct email address or username
- [ ] User has to type correct password
- [ ] After user logs in, they are redirected to the homepage
- [ ] If email or password is wrong an error alert is displayed

**Tasks**
Task 1: Implement login form
Task 2: Test functionality
